name: My second Github Action workflow

on: push


jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: install Cowsay library
              run: sudo apt install -y cowsay

            - name: execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I'm a DRAGON....RAWR" >> dragon.txt

            - name: upload Dragon text file 
              uses: actions/upload-artifact@v3
              with:
                name: dragonTXTFILE
                path: dragon.txt

                
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
            - name: download Dragon text file 
              uses: actions/download-artifact@v3
              with:
                name: dragonTXTFILE

            - name: Test file exists
              run: grep -i "dragon"dragon.txt


    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
            - name: download Dragon text file 
              uses: actions/download-artifact@v3
              with:
                name: dragonTXTFILE
            - name: read file
              run: cat dragon.txt

