name: My first Github Action workflow

on: push


jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/Checkout@v4

            - name: Welcome
              run: |
                echo "My First Github Actions job"
                ls -ltra
                cat README.md

            - name: run script in repo
              run: ./ascii-script.sh

            # - name: List Files
            #   run: ls -alh

            # - name: Read File
            #   run: cat README.md